"""Initial Migrations 3

Revision ID: 4c5b6a2fcb2c
Revises: 5e226586b441
Create Date: 2019-08-16 10:57:30.471646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c5b6a2fcb2c'
down_revision = '5e226586b441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('company', sa.String(), nullable=True))
    op.add_column('pitches', sa.Column('qualifications', sa.String(), nullable=True))
    op.add_column('pitches', sa.Column('state', sa.String(), nullable=True))
    op.create_index(op.f('ix_pitches_company'), 'pitches', ['company'], unique=False)
    op.create_index(op.f('ix_pitches_qualifications'), 'pitches', ['qualifications'], unique=False)
    op.create_index(op.f('ix_pitches_state'), 'pitches', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pitches_state'), table_name='pitches')
    op.drop_index(op.f('ix_pitches_qualifications'), table_name='pitches')
    op.drop_index(op.f('ix_pitches_company'), table_name='pitches')
    op.drop_column('pitches', 'state')
    op.drop_column('pitches', 'qualifications')
    op.drop_column('pitches', 'company')
    # ### end Alembic commands ###
